
-- More products for pagination demo
INSERT INTO public.products (name, description, type, category, price, period, image_url, features, demo_url)
VALUES
  ('Landing Page Pro', 'High-conversion landing page for marketing campaigns', 'Premium', 'Company Profile', 'Rp 149.000', '/sekali', 'https://images.unsplash.com/photo-1559028006-44a3a5f74e83?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"A/B Testing", "Lead Capture Form", "Analytics Integration", "Fast Loading"}', 'https://demo.example.com/landing-pro'),
  ('Blog Platform', 'A simple and elegant platform for writers and content creators', 'Non-Premium', 'CV / Portfolio', 'Rp 89.000', '/bulan', 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Markdown Editor", "SEO Friendly", "Custom Domain", "Comments"}', 'https://demo.example.com/blog-platform'),
  ('LMS Basic', 'Learning Management System for small courses', 'Non-Premium', 'Aplikasi Bisnis (ERP, POS, LMS, dll)', 'Rp 499.000', '/bulan', 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Course Creation", "Student Enrollment", "Quizzes", "Progress Tracking"}', 'https://demo.example.com/lms-basic'),
  ('Digital Invitation Basic', 'Undangan digital sederhana untuk berbagai acara', 'Non-Premium', 'Undangan Digital', 'Rp 49.000', '/sekali', 'https://images.unsplash.com/photo-1593504064303-013689405a08?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Simple Design", "Google Maps", "Photo Gallery"}', 'https://demo.example.com/invitation-basic'),
  ('E-Commerce Food Delivery', 'Platform e-commerce khusus untuk F&B', 'Premium', 'E-Commerce', 'Rp 799.000', '/bulan', 'https://images.unsplash.com/photo-1588675646184-f5b0b3b16b1e?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Menu Management", "Order Tracking", "Delivery Integration", "Promo System"}', 'https://demo.example.com/ecommerce-food'),
  ('Real Estate Listing', 'Website untuk agensi properti', 'Premium', 'Company Profile', 'Rp 499.000', '/bulan', 'https://images.unsplash.com/photo-1560518883-ce09059ee41f?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Property Listings", "Agent Profiles", "Mortgage Calculator", "Map View"}', 'https://demo.example.com/real-estate'),
  ('CRM for Sales Team', 'Customer Relationship Management untuk tim penjualan', 'Premium', 'Aplikasi Bisnis (ERP, POS, LMS, dll)', 'Rp 899.000', '/bulan', 'https://images.unsplash.com/photo-1556742211-53a65c270b52?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Contact Management", "Sales Pipeline", "Task Automation", "Reporting"}', 'https://demo.example.com/crm-sales'),
  ('Booking System', 'Sistem booking online untuk jasa', 'Non-Premium', 'Aplikasi Bisnis (ERP, POS, LMS, dll)', 'Rp 299.000', '/bulan', 'https://images.unsplash.com/photo-1521791136064-7986c2920216?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Calendar View", "Online Payments", "Email Reminders", "Staff Management"}', 'https://demo.example.com/booking-system'),
  ('Forum Komunitas', 'Platform diskusi online untuk komunitas', 'Non-Premium', 'E-Commerce', 'Rp 150.000', '/bulan', 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Topics & Replies", "User Profiles", "Moderation Tools", "Private Messaging"}', 'https://demo.example.com/forum'),
  ('Portfolio Fotografer', 'Website portfolio elegan untuk fotografer', 'Premium', 'CV / Portfolio', 'Rp 129.000', '/bulan', 'https://images.unsplash.com/photo-1505238680356-667803448bb6?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"High-res Galleries", "Client Proofing", "Watermarking", "Booking Form"}', 'https://demo.example.com/photographer-portfolio'),
  ('Website Sekolah', 'Sistem informasi sekolah yang terintegrasi', 'Premium', 'Company Profile', 'Rp 999.000', '/bulan', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Info Akademik", "Jadwal Pelajaran", "Portal Siswa/Guru", "Berita Sekolah"}', 'https://demo.example.com/school-website'),
  ('Aplikasi Kasir Mobile', 'Aplikasi POS sederhana untuk tablet dan smartphone', 'Non-Premium', 'Aplikasi Bisnis (ERP, POS, LMS, dll)', 'Rp 199.000', '/bulan', 'https://images.unsplash.com/photo-1587006766395-59c55b9a8f27?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Transaksi Cepat", "Manajemen Produk", "Struk Digital", "Laporan Harian"}', 'https://demo.example.com/mobile-pos'),
  ('Undangan Ulang Tahun', 'Undangan digital ceria untuk pesta ulang tahun', 'Non-Premium', 'Undangan Digital', 'Rp 29.000', '/sekali', 'https://images.unsplash.com/photo-1513151233558-d860c5398176?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Desain Tematik", "Galeri", "Hitung Mundur"}', 'https://demo.example.com/birthday-invitation'),
  ('Toko Online Fashion', 'E-commerce yang dioptimalkan untuk produk fashion', 'Premium', 'E-Commerce', 'Rp 699.000', '/bulan', 'https://images.unsplash.com/photo-1445205170230-053b83016050?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Varian Produk (Ukuran/Warna)", "Lookbook", "Integrasi Instagram", "Filter Lanjutan"}', 'https://demo.example.com/fashion-store'),
  ('Website Agensi Kreatif', 'Profil perusahaan untuk agensi desain/marketing', 'Non-Premium', 'Company Profile', 'Rp 129.000', '/bulan', 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Portofolio Proyek", "Tim Kami", "Testimonial", "Proses Kerja"}', 'https://demo.example.com/creative-agency'),
  ('CV Developer', 'Portfolio interaktif untuk developer software', 'Premium', 'CV / Portfolio', 'Rp 99.000', '/bulan', 'https://images.unsplash.com/photo-1534972195531-d756b9bfa9f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Integrasi GitHub", "Live Demo Proyek", "Timeline Karir", "Tech Stack Showcase"}', 'https://demo.example.com/dev-cv'),
  ('Sistem Antrian Online', 'Manajemen antrian untuk klinik, bank, atau layanan publik', 'Premium', 'Aplikasi Bisnis (ERP, POS, LMS, dll)', 'Rp 349.000', '/bulan', 'https://images.unsplash.com/photo-1542314831-068cd1dbb5ed?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Ambil Nomor Online", "Estimasi Waktu Tunggu", "Panggilan Suara", "Dashboard Monitor"}', 'https://demo.example.com/queue-system'),
  ('Website Restoran', 'Profil online untuk restoran dengan menu dan reservasi', 'Non-Premium', 'Company Profile', 'Rp 119.000', '/bulan', 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Menu Digital", "Reservasi Meja", "Galeri", "Info Kontak & Peta"}', 'https://demo.example.com/restaurant-site'),
  ('Toko Affiliate', 'Platform untuk membuat toko berbasis link affiliate', 'Non-Premium', 'E-Commerce', 'Rp 249.000', '/bulan', 'https://images.unsplash.com/photo-1556157382-97eda2d62296?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Import Produk Mudah", "Pelacakan Klik", "Kategori Kustom", "Desain Responsif"}', 'https://demo.example.com/affiliate-store'),
  ('Portal Berita Sederhana', 'Website untuk publikasi berita atau artikel', 'Non-Premium', 'Company Profile', 'Rp 199.000', '/bulan', 'https://images.unsplash.com/photo-1495020689067-958852a7765e?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Kategori Berita", "Halaman Penulis", "Sistem Komentar", "Trending Topics"}', 'https://demo.example.com/news-portal'),
  ('Manajemen Proyek Basic', 'Aplikasi untuk manajemen tugas dan proyek tim kecil', 'Non-Premium', 'Aplikasi Bisnis (ERP, POS, LMS, dll)', 'Rp 259.000', '/bulan', 'https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Papan Kanban", "Daftar Tugas", "Deadline", "File Sharing"}', 'https://demo.example.com/project-management-basic'),
  ('Undangan Acara Korporat', 'Undangan digital formal untuk acara bisnis', 'Premium', 'Undangan Digital', 'Rp 99.000', '/sekali', 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?ixlib=rb-4.0.3&auto=format&fit=crop&w=2340&q=80', '{"Desain Profesional", "Formulir Registrasi", "Agenda Acara", "Profil Pembicara"}', 'https://demo.example.com/corp-invitation');
